[package]
name = "control_flow-exercises"
version = "0.1.0"
authors = ["lmarin263 <lmarin263@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
